"""add ai_failure_summary

Revision ID: 3508002d5bff
Revises: 2e0f40aad2d4
Create Date: 2026-08-21 06:18:15.177963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3508002d5bff'
down_revision: Union[str, Sequence[str], None] = '2e0f40aad2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('ai_failure_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_executions', 'ai_failure_summary')
    # ### end Alembic commands ###
